git:
  submodules: false
language: perl
os:
  - linux
  - osx
perl:
  - "5.24"
  - "5.14"
  - "5.10"
matrix:
  exclude:
  - perl: "5.14"
    os: osx
  - perl: "5.10"
    os: osx
before_install: git submodule update --init
install: "make test-deps"
script: "make test-main"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "ircs://irc.suikawiki.org:6697#mechanize"
    use_notice: true
env:
  global:
    secure: "sJUFu7B+qqJKTWlTElNfRCZpVoauEHA8eTVFq9BNghwt0nVoG3yGQytYxptNkRdFBppV3LXfkaiBLnK+YVIf8idHoBjcAUoWxOt0gYXv9dtGmLFYzKzCXXranQW8oZl7xTddmJYX06tddTfgW3My1rriXbocvW40havj+Zq5AIo="
after_success:
  - curl -s -S -L https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
