=over 4

=item L<Web::HTTP::ConnectionClient>

A connection-oriented HTTP client.

=item L<Web::Transport::PlatformResolver>

A name resolver using system's resolver.

=item L<Web::Transport::CachedResolver>

A resolver cache.

=back

=head1 ENVIRONMENT VARIABLE

C<WEBUA_DEBUG> is XXX

=head1 DEPENDENCY

These module requires Perl 5.8 or later.

They also require L<Promise>.
