=head1 NAME

Web::Trasnport::ConstProxyManager - A constant-value proxy manager

=head1 SYNOPSIS

  use Web::Transport::ConstProxyManager;
  $pm = Web::Transport::ConstProxyManager->new_from_arrayref ($proxies);
  $pm->get_proxies_for_url ($url)->then (sub {
    $proxies = $_[0];
  });

=head1 DESCRIPTION

The C<Web::Transport::ConstProxyManager> object is a proxy manager,
which always returns a list of proxies specified when the proxy
manager is constructed.

This module is a proxy manager (see L<Web::Transport/"PROXY
MANAGERS">).

=head1 METHODS

Following methods are available:

=over 4

=item $pm = Web::Transport::ConstProxyManager->new_from_arrayref ($proxies)

Create a proxy manager.  The argument must be a proxy configuration
list (see L<Web::Transport/"PROXY CONFIGURATIONS">).

=item $promise = $pm->get_proxies_for_url ($url, $name => $value, ...)

Get the list of the proxies for the specified URL.  See
L<Web::Transport/"PROXY MANAGERS">.

=back

=head1 SPECIFICATION

Web Transport Processing
<https://wiki.suikawiki.org/n/Web%20Transport%20Processing>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2016-2018 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
