=head1 NAME

Web::Transport::ProxyServerConnection - HTTP proxy server connection

=head1 SYNOPSIS

  tcp_server $host, $port, sub {
    my $con = Web::Transport::ProxyServerConnection
        ->new_from_aeargs_and_opts ([@_], {...});
    $con->completed->then (sub {
      warn "Client disconnected and proxy done";
    });
  };

=head1 DESCRIPTION

The C<Web::Transport::ProxyServerConnection> module is an
implementation of HTTP proxy server.  It wraps an HTTP server's TCP
connection socket and forward any incoming request to upstream.

=head1 METHODS

See L<Web::Transport::GenericServerConnection/METHODS>.

=head1 SEE ALSO

L<AnyEvent::Socket>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2016-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
