=head1 NAME

Web::Transport::PSGIServerConnection - PSGI interface for HTTP server connection

=head1 SYNOPSIS

  $psgi_app = sub { ... };
  tcp_server $host, $port, sub {
    my $con = Web::Transport::PSGIServerConnection
        ->new_from_aeargs_and_opts ([@_], {psgi_app => $psgi_app});
    $con->completed->then (sub {
      warn "Client disconnected and PSGI application done";
    });
  };

=head1 DESCRIPTION

The C<Web::Transport::PSGIServerConnection> module is an
implementation of HTTP server and PSGI.  It wraps an HTTP server's TCP
connection socket and processes any incoming request by a PSGI
application.

=head1 METHODS

See L<Web::Transport::GenericServerConnection/METHODS>.

Use of the method C<new_from_app_and_ae_tcp_server_args> is
deprecated.  Use C<new_from_aeargs_and_opts> instead.

=head1 SEE ALSO

L<AnyEvent::Socket>.

=head1 SPECIFICATIONS

Web Transport Processing
<https://wiki.suikawiki.org/n/Web%20Transport%20Processing>.

RFC 3875, The Common Gateway Interface (CGI) Version 1.1
<https://tools.ietf.org/html/rfc3875>.

PSGI <https://github.com/plack/psgi-specs/blob/master/PSGI.pod>.

PSGI::Extensions
<https://github.com/plack/psgi-specs/blob/master/PSGI/Extensions.pod>.

C<psgix.exit_guard>
<https://github.com/kazeburo/Twiggy-Prefork#psgi-extensions>.

manakai PSGI extensions
<https://wiki.suikawiki.org/n/manakai%20PSGI%20extensions>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2016-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
